### ISSUE TITLE
Artist#shoot! should take a block to avoid having to manually unlink the tempfile

### ISSUE THREAD

**Issue by jhchabran** [TactilizeTeam/photograph#1]

**Comment by jhchabran** [comment]
``` ruby
artist.shoot! do |output|
    post callback_url, output
  end
end
```

**Comment by acoomans** [comment]
@jhchabran Tactilize, 10 ans après? 😄

**Comment by jhchabran** [comment]
@acoomans 🤣 

J'ai cliqué un peu partout et je suis arrivé là, c'était ouvert, j'ai fermé 😆 !

**Comment by tibastral** [comment]
La première issue haha. Si ça avait marché ce projet tu aurais pu la vendre en nft :)

**Comment by jorge-d** [comment]
Il est pas trop tard pour ça, une issue closed 10 ans après sur Github ca doit coter assez haut!
